### ISSUE TITLE
How to specify -nographic?

### ISSUE THREAD

**Issue by dydx** [runtimejs/runtime-tools#3]
Heya, nice project!

Running the examples, I kinda wished there were a way to specify the `-nographic` option in QEMU. Looking around the source, I do see that it _looks_ like it's implemented, but I can't figure out how to pass it as a command line flag.

I can manually set it in `runtime-qemu.js` as being `true`, but when I go to pass a parameter for it, `--nographic` is what it looks like it should be, I get the `usage` options shown at me.

What am I not doing right?

**Comment by iefserge** [comment]
@dydx Yeah, I see there is a command line parsing bug.
`runtime-qemu --nographic ./initrd` doesn't work, but `runtime-qemu --nographic=1 ./initrd` works.

**Comment by dydx** [comment]
Ah, alright. Thanks!

**Comment by iefserge** [comment]
This is fixed.

**Comment by dydx** [comment]
+1
